language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:pitti/systemd -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq systemd qt5base-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

